version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
